# File: .streamlit/secrets.toml

[supabase]
url = "https://sgeaclzmmzojuhfhregk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZWFjbHptbXpvanVoZmhyZWdrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Nzc0NzE5MSwiZXhwIjoyMDczMzIzMTkxfQ.Qi9IKvgGtIYlu2bFPjFmeuo0xQJkpUmPEw3sPFZjZCc"